version: '3.1'

services:
  web:
    container_name: recordstore-web-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=local
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=recordstore
      - MYSQL_USER=client
      - MYSQL_PASSWORD=client
      - MYSQL_ROOT_PASSWORD=root