version: '3.1'

services:
  web:
    image: brunoleonel/records-store
    container_name: recordstore-web
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    links:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    command: mvn flyway:migrate -Dflyway.configFiles=flywaydb-prod.conf
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=recordstore
      - MYSQL_USER=client
      - MYSQL_PASSWORD=client
      - MYSQL_ROOT_PASSWORD=root